---
title: "American Community Survey"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{acs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE, warning=FALSE}
library(dplyr)
library(people)
library(keyring)
library(tinytable)

tt_apollo <- function(tt) {
  tt |>
    style_tt(i = 0, color = "white", background = "#231f20")
}

profile <- get_profile(county = "Orange", state = "CA")
```


Here are some examples of how to use `people` to extract potentially useful population denominators.

### LHJ Total Population

Dataset: American Community Survey 5-Year

```{r county-pop, message=FALSE, warning=FALSE}
county_pop <- get_population(
  year = 2023,
  geography = "county",
  var = "B01003_001E",
  key = key_get("census_key"),
  county = profile$COUNTYFP,
  state = profile$STATEFP,
  dataset = "acs/acs5"
  )
```

```{r county-pop-print, echo=FALSE}
tt(county_pop) |>
  tt_apollo()
```

To pull multiple years at once:

```{r county-pop-years, message=FALSE, warning=FALSE}
years <- 2013:2023

rrr <- lapply(years,
              function(x) {
                get_population(
                  year = x,
                  geography = "county",
                  var = "B01003_001E",
                  key = key_get("census_key"),
                  county = profile$COUNTYFP,
                  state = profile$STATEFP,
                  dataset = "acs/acs5"
                  ) |>
                  mutate(year = x)
                }
              )
```

```{r county-pop-years-print, echo=FALSE}
rrr |>
  dplyr::bind_rows() |>
  tt(theme = "striped") |>
  tt_apollo()
```

### LHJ Population by Gender and Age Group

Dataset: American Community Survey 5-Year

```{r county-pop-gender-age, message=FALSE, warning=FALSE}
county_gender_age <- get_population(
  year = 2019,
  geography = "county",
  var = "group(B01001)",
  key = key_get("census_key"),
  county = profile$COUNTYFP,
  state = profile$STATEFP,
  dataset = "acs/acs5"
  )
```

```{r county-pop-gender-age-print, echo=FALSE}
county_gender_age |>
  head(10) |>
  tt(theme = "striped") |>
  tt_apollo()
```

### Total Zip Code Population

Dataset: American Community Survey 5-Year

```{r zip-pop, message=FALSE, warning=FALSE}
zip_pop <- get_population(
  year = 2015,
  geography = "zip code",
  geo_id = "92706",
  var = "B01003_001E",
  key = key_get("census_key"),
  county = profile$COUNTYFP,
  state = profile$STATEFP,
  dataset = "acs/acs5"
  )
```

```{r zip-pop-print, echo=FALSE}
tt(zip_pop) |>
  tt_apollo()
```