---
title: "County"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{county}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE, warning=FALSE}
library(dplyr)
library(people)
library(keyring)
library(tinytable)

tt_apollo <- function(tt) {
  tt |>
    style_tt(i = 0, color = "white", background = "#231f20")
}

profile <- get_profile(county = "Orange", state = "CA")

vars <- census_vars(year = 2023, dataset = "acs/acs5")
```


The following examples use the American Community Survey 5-Year for county level population estimates.

### Total County Population

Single year:

```{r county-pop-year, message=FALSE, warning=FALSE, include=FALSE}
ppp <- get_population(
  year = 2023,
  geography = "county",
  var = "B01003_001E",
  key = key_get("census_key"),
  county = profile$COUNTYFP,
  state = profile$STATEFP,
  dataset = "acs/acs5"
  )
```

Multiple years:

```{r county-pop-years, message=FALSE, warning=FALSE}
years <- 2013:2023

rrr <- lapply(years,
              function(x) {
                get_population(
                  year = x,
                  geography = "county",
                  var = "B01003_001E",
                  key = key_get("census_key"),
                  county = profile$COUNTYFP,
                  state = profile$STATEFP,
                  dataset = "acs/acs5"
                  )
                }
              ) |>
  dplyr::bind_rows()

rrr |>
  tt(theme = "striped") |>
  tt_apollo()
```

### Gender and Age Group

```{r county-gender-age, message=FALSE, warning=FALSE}
ccc <- get_population(
  year = 2023,
  geography = "county",
  var = "group(B01001)",
  key = key_get("census_key"),
  county = profile$COUNTYFP,
  state = profile$STATEFP,
  dataset = "acs/acs5"
  )

ccc <- left_join(ccc, vars, by = c("variable"="name"))

ccc |>
  tt(theme = "striped") |>
  tt_apollo()
```

### Race/Ethnicity

